# Generated by Django 3.1.3 on 2020-11-19 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0004_token_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='hash',
        ),
    ]
