# Generated by Django 3.1.3 on 2020-11-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0005_auto_20201119_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
    ]
