# Generated by Django 3.1.3 on 2020-11-20 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0007_auto_20201120_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
