# Generated by Django 3.1.3 on 2020-11-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0009_auto_20201120_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='a', max_length=100, unique=True),
        ),
    ]
