# Generated by Django 3.1.3 on 2020-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0012_auto_20201120_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='c4b0b5c0-8519-428d-afa6-1b534a31c9e1', max_length=100, unique=True),
        ),
    ]
