# Generated by Django 3.1.3 on 2020-11-21 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0013_auto_20201120_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='b2b8cf2c-f10d-430c-ab1f-b1f43ea33d3f', max_length=100, unique=True),
        ),
    ]
