# Generated by Django 3.1.3 on 2020-11-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0014_auto_20201121_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='5d94a6d0-cd31-4b5c-9ee4-ecde8bb0c448', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(),
        ),
    ]
