# Generated by Django 3.1.3 on 2020-11-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0015_auto_20201121_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='e909a7c6-5f7b-4ff2-8e1e-bffe509ce658', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
