# Generated by Django 3.1.3 on 2020-11-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0016_auto_20201121_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='d652251c-1e38-4098-a811-b3357550b4f1', max_length=100, unique=True),
        ),
    ]
