# Generated by Django 3.1.3 on 2020-11-21 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0018_auto_20201121_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='c4b2dedb-a9a5-41e4-b579-3be7fffb80ed', max_length=100, unique=True),
        ),
    ]
