# Generated by Django 3.1.3 on 2020-11-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0019_auto_20201121_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='3d5fc4a4-801c-4d20-a27f-7034eaadeedd', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('number', 'area_code', 'country_code')},
        ),
    ]
