# Generated by Django 3.1.3 on 2020-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0020_auto_20201121_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='hash',
            field=models.CharField(default='94d45f54-dffa-43a9-aa0e-5fffc4169c24', max_length=100, unique=True),
        ),
    ]
